name: Flutter Analyze

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  analyze:
    name: Analyze with Dart
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ’¾ Install Flutter
        cache: true
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: ðŸ“¦ Install dependencies
        run: flutter pub get

      - name: ðŸ§ª Run Dart Analyzer
        run: dart analyze
